services:
  - type: web
    name: meridian-dca-api
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CHAIN_ID
        value: 31337
      - key: RPC_URL
        value: http://127.0.0.1:8545
      - key: FRONTEND_ORIGIN
        sync: false
      - key: DCA_MANAGER_ADDRESS
        value: 0x5FbDB2315678afecb367f032d93F642f64180aa3
      - key: VAULT_ADAPTER_ADDRESS
        value: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      - key: YIELD_VAULT_ADDRESS
        value: 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
      - key: EXECUTION_CONTRACT_ADDRESS
        value: 0x9A676e781A523b5d0C0e43731313A708CB607508
      - key: DCA_HOOK_ADDRESS
        value: 0xCf7Ed3AccA5a467e9e75457215744945220f6844
      - key: MARKET_ORACLE_ADDRESS
        value: 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
